-- Treasure Hunt / ตามล่าหาสมบัติ
-- Run this file in Supabase SQL Editor once for a new project.

create extension if not exists pgcrypto;

-- =========================
-- TABLES
-- =========================

create table if not exists public.students (
  id uuid primary key default gen_random_uuid(),
  student_code text not null unique,
  prefix text not null default '',
  first_name text not null,
  last_name text not null default '',
  class_name text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.questions (
  id uuid primary key default gen_random_uuid(),
  sign_number integer not null check (sign_number between 1 and 43),
  question_slot integer not null check (question_slot between 1 and 3),
  question_text text not null default '',
  option_a text not null default '',
  option_b text not null default '',
  option_c text not null default '',
  option_d text not null default '',
  correct_option text not null default 'A' check (correct_option in ('A','B','C','D')),
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(sign_number, question_slot)
);

create table if not exists public.game_sessions (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null unique references public.students(id) on delete cascade,
  session_token_hash text not null unique,
  status text not null default 'active' check (status in ('active','ended','completed')),
  correct_count integer not null default 0 check (correct_count between 0 and 25),
  wrong_count integer not null default 0 check (wrong_count >= 0),
  chests_opened integer not null default 0 check (chests_opened between 0 and 2),
  awaiting_chest boolean not null default false,
  current_question_id uuid references public.questions(id),
  current_sign_number integer check (current_sign_number between 1 and 43),
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  last_activity_at timestamptz not null default now()
);

create table if not exists public.game_answer_attempts (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.game_sessions(id) on delete cascade,
  question_id uuid not null references public.questions(id),
  sign_number integer not null check (sign_number between 1 and 43),
  selected_option text not null check (selected_option in ('A','B','C','D')),
  is_correct boolean not null,
  answered_at timestamptz not null default now()
);

create index if not exists idx_attempts_session on public.game_answer_attempts(session_id);
create index if not exists idx_attempts_session_sign on public.game_answer_attempts(session_id, sign_number);
create index if not exists idx_questions_active_sign on public.questions(is_active, sign_number);

-- Seed 43 signs x 3 question slots = 129 editable rows.
insert into public.questions (sign_number, question_slot)
select s.sign_number, q.question_slot
from generate_series(1,43) as s(sign_number)
cross join generate_series(1,3) as q(question_slot)
on conflict (sign_number, question_slot) do nothing;

-- =========================
-- RLS: browser cannot read/write tables directly.
-- Student game uses only SECURITY DEFINER RPC functions below.
-- Admin uses an Edge Function with the service-role key.
-- =========================

alter table public.students enable row level security;
alter table public.questions enable row level security;
alter table public.game_sessions enable row level security;
alter table public.game_answer_attempts enable row level security;

revoke all on table public.students from anon, authenticated;
revoke all on table public.questions from anon, authenticated;
revoke all on table public.game_sessions from anon, authenticated;
revoke all on table public.game_answer_attempts from anon, authenticated;
revoke all on sequence public.game_answer_attempts_id_seq from anon, authenticated;

-- =========================
-- HELPERS
-- =========================

create or replace function public._token_hash(p_token text)
returns text
language sql
immutable
set search_path = public
as $$
  select encode(digest(coalesce(p_token,''), 'sha256'), 'hex');
$$;

create or replace function public._question_payload(
  p_question_id uuid,
  p_sign_number integer,
  p_sequence integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  q public.questions%rowtype;
begin
  select * into q from public.questions where id = p_question_id;
  if not found then
    return jsonb_build_object('ok', false, 'error', 'question_not_found');
  end if;

  -- IMPORTANT: never return question_text or correct_option to the student browser.
  return jsonb_build_object(
    'ok', true,
    'question', jsonb_build_object(
      'signNumber', p_sign_number,
      'sequence', p_sequence,
      'choices', jsonb_build_array(
        jsonb_build_object('key','A','text',q.option_a),
        jsonb_build_object('key','B','text',q.option_b),
        jsonb_build_object('key','C','text',q.option_c),
        jsonb_build_object('key','D','text',q.option_d)
      )
    )
  );
end;
$$;

-- =========================
-- STUDENT RPC API
-- =========================

create or replace function public.lookup_student(p_student_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  st public.students%rowtype;
  gs public.game_sessions%rowtype;
  full_name text;
begin
  select * into st
  from public.students
  where student_code = trim(p_student_code)
    and is_active = true;

  if not found then
    return jsonb_build_object('found', false, 'message', 'ไม่พบรหัสนักเรียน');
  end if;

  full_name := trim(concat_ws(' ', nullif(st.prefix,''), st.first_name, nullif(st.last_name,'')));

  select * into gs from public.game_sessions where student_id = st.id;

  if found then
    return jsonb_build_object(
      'found', true,
      'eligible', false,
      'studentCode', st.student_code,
      'name', full_name,
      'className', st.class_name,
      'playStatus', gs.status,
      'score', gs.correct_count,
      'message', case gs.status
        when 'completed' then 'นักเรียนคนนี้เล่นครบ 25 ข้อแล้ว'
        when 'ended' then 'นักเรียนคนนี้จบเกมแล้ว'
        else 'นักเรียนคนนี้มีเกมที่เริ่มไว้แล้ว กรุณาเล่นต่อจากอุปกรณ์เดิม'
      end
    );
  end if;

  return jsonb_build_object(
    'found', true,
    'eligible', true,
    'studentCode', st.student_code,
    'name', full_name,
    'className', st.class_name
  );
end;
$$;

create or replace function public.start_game(p_student_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  st public.students%rowtype;
  new_token text;
  gs_id uuid;
  full_name text;
begin
  select * into st
  from public.students
  where student_code = trim(p_student_code)
    and is_active = true
  for update;

  if not found then
    return jsonb_build_object('ok', false, 'error', 'student_not_found', 'message', 'ไม่พบรหัสนักเรียน');
  end if;

  if exists (select 1 from public.game_sessions where student_id = st.id) then
    return jsonb_build_object('ok', false, 'error', 'already_played', 'message', 'รหัสนักเรียนนี้เริ่มเล่นแล้ว ไม่สามารถเริ่มรอบใหม่ได้');
  end if;

  -- Do not lock a student into a session until at least 25 complete signs are ready.
  -- A complete sign has all 3 active questions with A-D filled in.
  if (
    select count(*) from (
      select q.sign_number
      from public.questions q
      where q.is_active = true
        and q.option_a <> '' and q.option_b <> '' and q.option_c <> '' and q.option_d <> ''
      group by q.sign_number
      having count(*) = 3
    ) ready_signs
  ) < 25 then
    return jsonb_build_object(
      'ok', false,
      'error', 'game_not_ready',
      'message', 'ข้อสอบยังไม่พร้อม ต้องมีอย่างน้อย 25 ป้ายที่เปิดใช้งานครบป้ายละ 3 ข้อ'
    );
  end if;

  new_token := gen_random_uuid()::text || '-' || gen_random_uuid()::text;

  insert into public.game_sessions(student_id, session_token_hash)
  values (st.id, public._token_hash(new_token))
  returning id into gs_id;

  full_name := trim(concat_ws(' ', nullif(st.prefix,''), st.first_name, nullif(st.last_name,'')));

  return jsonb_build_object(
    'ok', true,
    'sessionToken', new_token,
    'student', jsonb_build_object(
      'studentCode', st.student_code,
      'name', full_name,
      'className', st.class_name
    ),
    'score', 0,
    'chestsOpened', 0
  );
exception
  when unique_violation then
    return jsonb_build_object('ok', false, 'error', 'already_played', 'message', 'รหัสนักเรียนนี้เริ่มเล่นแล้ว ไม่สามารถเริ่มรอบใหม่ได้');
end;
$$;

create or replace function public.get_game_state(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  gs public.game_sessions%rowtype;
  st public.students%rowtype;
  payload jsonb;
  full_name text;
begin
  select * into gs
  from public.game_sessions
  where session_token_hash = public._token_hash(p_session_token);

  if not found then
    return jsonb_build_object('ok', false, 'error', 'invalid_session');
  end if;

  select * into st from public.students where id = gs.student_id;
  full_name := trim(concat_ws(' ', nullif(st.prefix,''), st.first_name, nullif(st.last_name,'')));

  payload := jsonb_build_object(
    'ok', true,
    'status', gs.status,
    'score', gs.correct_count,
    'wrongCount', gs.wrong_count,
    'chestsOpened', gs.chests_opened,
    'awaitingChest', gs.awaiting_chest,
    'student', jsonb_build_object(
      'studentCode', st.student_code,
      'name', full_name,
      'className', st.class_name
    )
  );

  if gs.status <> 'active' then
    return payload || jsonb_build_object(
      'finished', true,
      'bigReward', gs.status = 'completed',
      'room', '738'
    );
  end if;

  if gs.awaiting_chest then
    return payload || jsonb_build_object(
      'milestone', gs.correct_count,
      'chestNumber', gs.chests_opened
    );
  end if;

  if gs.current_question_id is not null then
    return payload || (public._question_payload(gs.current_question_id, gs.current_sign_number, gs.correct_count + 1) - 'ok');
  end if;

  return payload;
end;
$$;

create or replace function public.next_question(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  gs public.game_sessions%rowtype;
  chosen_sign integer;
  q public.questions%rowtype;
begin
  select * into gs
  from public.game_sessions
  where session_token_hash = public._token_hash(p_session_token)
  for update;

  if not found then
    return jsonb_build_object('ok', false, 'error', 'invalid_session');
  end if;

  if gs.status <> 'active' then
    return jsonb_build_object('ok', false, 'error', 'game_finished');
  end if;

  if gs.awaiting_chest then
    return jsonb_build_object('ok', false, 'error', 'chest_action_required', 'milestone', gs.correct_count);
  end if;

  if gs.correct_count >= 25 then
    return jsonb_build_object('ok', false, 'error', 'game_finished');
  end if;

  if gs.current_question_id is not null then
    return public._question_payload(gs.current_question_id, gs.current_sign_number, gs.correct_count + 1);
  end if;

  -- Choose a SIGN uniformly, excluding every sign already attempted in this session.
  select es.sign_number into chosen_sign
  from (
    select q2.sign_number
    from public.questions q2
    where q2.is_active = true
      and q2.option_a <> '' and q2.option_b <> '' and q2.option_c <> '' and q2.option_d <> ''
      and not exists (
        select 1
        from public.game_answer_attempts a
        where a.session_id = gs.id
          and a.sign_number = q2.sign_number
      )
    group by q2.sign_number
    having count(*) = 3
  ) es
  order by random()
  limit 1;

  if chosen_sign is null then
    return jsonb_build_object(
      'ok', false,
      'error', 'not_enough_questions',
      'message', 'ข้อสอบที่เปิดใช้งานมีไม่พอสำหรับเล่นต่อ กรุณาแจ้งครูผู้ดูแล'
    );
  end if;

  -- Then choose 1 of up to 3 active questions on that sign.
  select * into q
  from public.questions
  where sign_number = chosen_sign
    and is_active = true
    and option_a <> '' and option_b <> '' and option_c <> '' and option_d <> ''
  order by random()
  limit 1;

  update public.game_sessions
  set current_question_id = q.id,
      current_sign_number = chosen_sign,
      last_activity_at = now()
  where id = gs.id;

  return public._question_payload(q.id, chosen_sign, gs.correct_count + 1);
end;
$$;

create or replace function public.submit_answer(p_session_token text, p_selected_option text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  gs public.game_sessions%rowtype;
  q public.questions%rowtype;
  selected text;
  is_right boolean;
  new_count integer;
  new_chests integer;
begin
  selected := upper(trim(p_selected_option));
  if selected not in ('A','B','C','D') then
    return jsonb_build_object('ok', false, 'error', 'invalid_option');
  end if;

  select * into gs
  from public.game_sessions
  where session_token_hash = public._token_hash(p_session_token)
  for update;

  if not found then
    return jsonb_build_object('ok', false, 'error', 'invalid_session');
  end if;

  if gs.status <> 'active' then
    return jsonb_build_object('ok', false, 'error', 'game_finished');
  end if;

  if gs.awaiting_chest then
    return jsonb_build_object('ok', false, 'error', 'chest_action_required');
  end if;

  if gs.current_question_id is null then
    return jsonb_build_object('ok', false, 'error', 'no_current_question');
  end if;

  select * into q from public.questions where id = gs.current_question_id;
  if not found then
    return jsonb_build_object('ok', false, 'error', 'question_not_found');
  end if;

  is_right := (selected = q.correct_option);

  insert into public.game_answer_attempts(session_id, question_id, sign_number, selected_option, is_correct)
  values (gs.id, q.id, gs.current_sign_number, selected, is_right);

  if not is_right then
    update public.game_sessions
    set wrong_count = wrong_count + 1,
        last_activity_at = now()
    where id = gs.id;

    return jsonb_build_object(
      'ok', true,
      'correct', false,
      'score', gs.correct_count,
      'message', 'ยังไม่ถูก ลองอีกครั้ง'
    );
  end if;

  new_count := gs.correct_count + 1;
  new_chests := gs.chests_opened;

  if new_count = 10 then new_chests := greatest(new_chests, 1); end if;
  if new_count = 20 then new_chests := greatest(new_chests, 2); end if;

  if new_count >= 25 then
    update public.game_sessions
    set correct_count = 25,
        chests_opened = new_chests,
        current_question_id = null,
        current_sign_number = null,
        awaiting_chest = false,
        status = 'completed',
        ended_at = now(),
        last_activity_at = now()
    where id = gs.id;

    return jsonb_build_object(
      'ok', true,
      'correct', true,
      'score', 25,
      'chestsOpened', new_chests,
      'finished', true,
      'bigReward', true,
      'room', '738',
      'message', 'ยินดีด้วย! คุณตอบครบ 25 ข้อและได้รับรางวัลใหญ่'
    );
  end if;

  if new_count in (10,20) then
    update public.game_sessions
    set correct_count = new_count,
        chests_opened = new_chests,
        current_question_id = null,
        current_sign_number = null,
        awaiting_chest = true,
        last_activity_at = now()
    where id = gs.id;

    return jsonb_build_object(
      'ok', true,
      'correct', true,
      'score', new_count,
      'chestsOpened', new_chests,
      'milestone', true,
      'chestNumber', new_chests,
      'message', 'ยินดีด้วย! เปิดหีบสมบัติได้แล้ว'
    );
  end if;

  update public.game_sessions
  set correct_count = new_count,
      current_question_id = null,
      current_sign_number = null,
      last_activity_at = now()
  where id = gs.id;

  return jsonb_build_object(
    'ok', true,
    'correct', true,
    'score', new_count,
    'chestsOpened', new_chests,
    'message', 'ตอบถูก!'
  );
end;
$$;

create or replace function public.continue_game(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  gs public.game_sessions%rowtype;
begin
  select * into gs
  from public.game_sessions
  where session_token_hash = public._token_hash(p_session_token)
  for update;

  if not found then
    return jsonb_build_object('ok', false, 'error', 'invalid_session');
  end if;

  if gs.status <> 'active' then
    return jsonb_build_object('ok', false, 'error', 'game_finished');
  end if;

  if not gs.awaiting_chest then
    return jsonb_build_object('ok', false, 'error', 'not_at_milestone');
  end if;

  update public.game_sessions
  set awaiting_chest = false,
      last_activity_at = now()
  where id = gs.id;

  return jsonb_build_object('ok', true, 'score', gs.correct_count, 'continue', true);
end;
$$;

create or replace function public.finish_game(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  gs public.game_sessions%rowtype;
begin
  select * into gs
  from public.game_sessions
  where session_token_hash = public._token_hash(p_session_token)
  for update;

  if not found then
    return jsonb_build_object('ok', false, 'error', 'invalid_session');
  end if;

  if gs.status <> 'active' then
    return jsonb_build_object('ok', true, 'finished', true, 'score', gs.correct_count, 'room', '738');
  end if;

  -- Students may voluntarily finish only at the 10/20-question chest milestone.
  if not gs.awaiting_chest or gs.correct_count not in (10,20) then
    return jsonb_build_object('ok', false, 'error', 'finish_not_allowed', 'message', 'สามารถจบเกมได้เมื่อเปิดหีบที่ 10 หรือ 20 ข้อ');
  end if;

  update public.game_sessions
  set status = 'ended',
      awaiting_chest = false,
      ended_at = now(),
      last_activity_at = now()
  where id = gs.id;

  return jsonb_build_object(
    'ok', true,
    'finished', true,
    'bigReward', false,
    'score', gs.correct_count,
    'chestsOpened', gs.chests_opened,
    'room', '738',
    'message', 'ยินดีด้วย! คุณจบภารกิจตามล่าหาสมบัติแล้ว'
  );
end;
$$;

-- Lock down helper functions from direct browser use where not required.
revoke all on function public._token_hash(text) from public, anon, authenticated;
revoke all on function public._question_payload(uuid, integer, integer) from public, anon, authenticated;

revoke all on function public.lookup_student(text) from public;
revoke all on function public.start_game(text) from public;
revoke all on function public.get_game_state(text) from public;
revoke all on function public.next_question(text) from public;
revoke all on function public.submit_answer(text,text) from public;
revoke all on function public.continue_game(text) from public;
revoke all on function public.finish_game(text) from public;

grant execute on function public.lookup_student(text) to anon, authenticated;
grant execute on function public.start_game(text) to anon, authenticated;
grant execute on function public.get_game_state(text) to anon, authenticated;
grant execute on function public.next_question(text) to anon, authenticated;
grant execute on function public.submit_answer(text,text) to anon, authenticated;
grant execute on function public.continue_game(text) to anon, authenticated;
grant execute on function public.finish_game(text) to anon, authenticated;

-- Optional: keep updated_at current when edited from Admin.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_students_updated_at on public.students;
create trigger trg_students_updated_at
before update on public.students
for each row execute function public.set_updated_at();

drop trigger if exists trg_questions_updated_at on public.questions;
create trigger trg_questions_updated_at
before update on public.questions
for each row execute function public.set_updated_at();
